# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# fzf-tab - must load after compinit (prezto handles that above)
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/contrib/fzf-tab/fzf-tab.plugin.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/contrib/fzf-tab/fzf-tab.plugin.zsh"
fi

# ---- fzf-tab config ----
# Enable group headers (e.g. "common commands", "branches" in git completion)
# Groups cycle with < and >
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:*' switch-group '<' '>'
# Colorize file completions
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# Don't show zsh's built-in menu (let fzf-tab handle it)
zstyle ':completion:*' menu no
# Don't sort git checkout completions (show in natural order)
zstyle ':completion:*:git-checkout:*' sort false
# Preview commands - edit these to change previews for all commands in each group
_fzf_preview_dir='eza -1 --color=always $realpath'
_fzf_preview_file='bat --color=always --style=numbers --line-range=:200 $realpath 2>/dev/null'

# Directory previews
for cmd in cd ls ll la eza pushd; do
  zstyle ":fzf-tab:complete:$cmd:*" fzf-preview "$_fzf_preview_dir"
done
# File previews
for cmd in cat bat vim nvim lgv; do
  zstyle ":fzf-tab:complete:$cmd:*" fzf-preview "$_fzf_preview_file"
done
# Git branch/ref previews
zstyle ':fzf-tab:complete:git-(checkout|switch|branch|merge|rebase|diff|log):*' fzf-preview 'git log --oneline --color=always -20 $word 2>/dev/null'
# Process previews
zstyle ':fzf-tab:complete:kill:*' fzf-preview 'ps -p $word -o pid,user,%cpu,%mem,command 2>/dev/null'
# Environment variable previews
zstyle ':fzf-tab:complete:export:*' fzf-preview 'echo ${(P)word}'
# SSH host previews
zstyle ':fzf-tab:complete:ssh:*' fzf-preview 'echo "Host: $word"'
# Use / to accept and continue completing (drill into directories)
zstyle ':fzf-tab:*' continuous-trigger '/'
# Use tmux popup for fzf-tab completions (requires tmux 3.2+)
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-min-size 120 30
zstyle ':fzf-tab:*' popup-size 120 50
# ---- end fzf-tab config ----

# Aliases

# Stop prompting to remove every file
# unalias rm
alias rm='nocorrect rm'
alias cp='nocorrect cp'
alias mv='nocorrect mv'

alias cd..='cd ..'
alias ..='cd ..'
alias cd-='cd -'

alias up='git fetch && git rebase origin/main'
alias uploc='git rebase origin/main'
alias pb="cd ~/code/my_repo; printf '\\033kmy_repo\\033\\\\'"
alias b='~/scripts/build.py'
alias u='~/scripts/upload.py'
alias wiki='pushd ~/vimwiki && wiki -g ~/vimwiki/index.wiki && popd'
alias synczsh='rsync -aPvh ~/.zprezto/ target_machine:/home/jbrewer/.zprezto'
alias less='less -R'
alias rgp='rg -t py'

alias tclip='tmux show-buffer | pbcopy'
alias treload='tmux source-file ~/.tmux.conf && echo "tmux config reloaded"'

alias pip='pip3'
alias python='python3'

# ge - expand scmpuff numeric args ($e1, $e2, ...) for any command
# e.g. `ge vim 1 2` → `vim $e1 $e2`
ge() {
  local cmd="$1"; shift
  local args=()
  for arg in "$@"; do
    if [[ "$arg" =~ ^[0-9]+$ ]]; then
      local var="e${arg}"
      args+=("${(P)var}")
    else
      args+=("$arg")
    fi
  done
  "$cmd" "${args[@]}"
}

title () {
  printf '\033k'
  printf $@
  printf '\033\\'
}

function rename_tab {
  # Note: May require tmux set-option -g set-titles on
  echo -ne "\033]0;"$@"\007"
}
rename_tab zsh

say () {
  printf '\x1bPtmux;\x1b\x1b]9;'
  printf $@
  printf "\x07\x1b\\"
}

SYNC_OTHER_FILES='\
  ~/.scmbrc \
  ~/.git.scmbrc \
  ~/.gitconfig \
  ~/.bash_custom \
  ~/scripts \
'
alias syncother="\
  rsync -aPvh --exclude '.*.swp' $SYNC_OTHER_FILES target_machine:/home/jbrewer/ &&
  rsync -aPvh --exclude '.*.swp' $SYNC_OTHER_FILES target_machine2:/home/jbrewer/
"

alias sw='git checkout'
alias br='git branch'
alias gs='git status'

alias mailme='~/scripts/send-mail.py -t jbrewer@company.com -l $? -s'

# Machine specific aliases
if [[ $HOME == "/Users/$USER" ]]; then
  # E.g. running on a mac
  alias dev='ssh target_machine'
  alias ll='eza -l --git --hyperlink --header'

  export MY_HOST_NAME='laptop'

  alias cln="echo Probably want to clean server, otherwise: git reset --hard \&\& git clean -fd --exclude virtualenv"
  alias ws='touch test.txt; sleep 1; rm test.txt'
  alias gvim='ge mvim'

  alias tmwatch="teamocil --layout ~/scripts/teamocil_watch.yaml --here"

  alias devml='cd ~/code/ml && VIRTUAL_ENV_DISABLE_PROMPT=1 source ~/code/dev/bin/activate'
  alias undev='deactivate'
else
  # Server
  alias st='zsh'
  alias stt='tmux source-file ~/.tmux.conf'
  alias ls='ls -F --color'
  alias ll='eza -l --git --header'
  alias cln='git reset --hard && git clean -fd --exclude virtualenv'
  fixssh() {
    eval $(tmux show-env | sed -n 's/^\(SSH_[^=]*\)=\(.*\)/export \1="\2"/p')
  }

  if [[ `hostname` =~ '^.*jbrewer$' ]]; then
    export MY_HOST_NAME='specific_server'

    alias att='cd ~/code/my_repo && tmux attach -t session_name'
    alias attac='tmux new-session -s session_name'
  elif [[ `hostname` =~ 'another-host-.*' ]]; then
    export MY_HOST_NAME='another_server'

    # E.g. tmux in specific path for shared server
    alias att='tmux -S ~/tmux-sockets/dev attach'
    alias attac='tmux -S ~/tmux-sockets/dev new-session'
  else
    export MY_HOST_NAME='another_server'

    alias km='~/scripts/kill_proc.sh a'
    alias kb='~/scripts/kill_proc.sh b'
  fi
  alias nb='jupyter notebook --port 46780 --no-browser'
fi

# Paths
export PATH=~/bin:$PATH
export PATH=~/scripts:$PATH

# Zsh options
setopt AUTO_PUSHD
# ls c* shows a list instead of inserting matching
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
setopt PUSHD_IGNORE_DUPS

setopt ZLE
setopt IGNORE_EOF

setopt NO_FLOW_CONTROL

setopt EXTENDED_GLOB
setopt NUMERIC_GLOB_SORT
setopt RC_EXPAND_PARAM

# Overwrite files with a pipe
setopt CLOBBER

# Allow comments inline in the shell
setopt interactivecomments

setopt INC_APPEND_HISTORY
HISTSIZE=100000
SAVEHIST=100000

export CLICOLOR=1

export EDITOR=vim
export VISUAL=vim

# Dasht {
export MANPATH=~/bin/dasht/man
export PATH=~/bin/dasht/bin:$PATH
export DASHT_DOCSETS_DIR=~/bin/dasht/docsets
# }

# Scm puff
# Note: scmpuff doesn't correctly handle paths (try git checkout -b my_branch)
eval "$(scmpuff init -s)"

# Note: Use cat -v then type characters to find the right codes
bindkey 'ƒ' emacs-forward-word
bindkey '∫' emacs-backward-word
# Idea is up/down are search-including-substrings, ctrl-p/ctrl-n are prefix only
# https://www.reddit.com/r/zsh/comments/wpicho/debugging_overwritten_bindkey_cmds/
# - up/down are also hard to rebind, something overrides bindkey within prezto,
# but these work
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^P' up-line-or-beginning-search
bindkey '^N' down-line-or-beginning-search

source ~/.zshrc-snap

# From
# https://stackoverflow.com/questions/9810327/zsh-auto-completion-for-git-takes-significant-amount-of-time-can-i-turn-it-off
# - should fix very slow autocomplete for possibly-remote items
__git_files () {
  _wanted files expl 'local files' _files
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/.local/bin:$PATH"

# fzf - fuzzy finder (Ctrl-R history, Ctrl-T files, Ctrl-F cd into dir)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND='fd --type f'
export FZF_CTRL_T_OPTS="--tmux 80%,80% --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
export FZF_ALT_C_COMMAND='fd --type d'
export FZF_ALT_C_OPTS="--tmux 80%,80% --preview 'eza --tree --level=2 --color=always {}'"
export FZF_CTRL_R_OPTS="--tmux 80%,80% --preview 'echo {}' --preview-window=up:3:wrap"

# Rebind fzf directory jump from Alt-C to Ctrl-F
bindkey -r '\ec'
bindkey '^F' fzf-cd-widget

# zoxide - directory jumping (z <query>, zi for interactive)
eval "$(zoxide init zsh)"

# fast-syntax-highlighting (replaces zsh-syntax-highlighting)
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/contrib/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/contrib/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
fi

# atuin - shell history (local mode, no sync)
eval "$(atuin init zsh --disable-up-arrow)"

